import catalog from "./exercise-catalog.json";

/** One entry per illustrated exercise (all 302 from bryllim/workout-guide).
 *  Regenerated by `scripts/sync-exercise-art.mjs` — don't edit the JSON. */
export interface ExerciseCatalogEntry {
  /** Hyphenated art slug, also the folder under `public/exercise-art/`. */
  slug: string;
  name: string;
  /** e.g. "Barbell", "Machine", "Resistance Band" — see the library filters. */
  equipment: string;
  primaryMuscle: string;
  secondaryMuscles: string[];
  isStretch: boolean;
}

export const EXERCISE_CATALOG = catalog as ExerciseCatalogEntry[];
